---

# You can add additinal measurements from
# https://atlas.ripe.net/measurements/

ripeAtlasMeasurements:
        measurement11401:
                measurementNumber: 13027
                startSecondsBeforeNow: 300
        measurement2006:
                measurementNumber: 2006
                startSecondsBeforeNow: 3000
        measurement30002:
                measurementNumber: 30002
                startSecondsBeforeNow: 3000
